SELECT TO_CHAR(SYSDATE-7, 'YYYYWW') FROM DUAL
SELECT TO_CHAR(SYSDATE, 'YYYYWW') FROM DUAL
SELECT TO_CHAR(SYSDATE-30, 'YYYYMMDD') FROM DUAL
SELECT TO_CHAR(SYSDATE, 'YYYYMMDD') FROM DUAL
SELECT TO_CHAR(SYSDATE-1, 'YYYYMMDD') FROM DUAL
