CREATE TABLE REGION_INFO(
    REGION_NUM VARCHAR2(200),
    REGION_NAME VARCHAR2(200),
    CONSTRAINTS PK_REGION_INFO PRIMARY KEY (REGION_NUM)
    );
   
CREATE TABLE PRODUCT_INFO(
    PRODUCT_NUM VARCHAR2(200),
    PRODUCT_NAME VARCHAR2(200),
    AVG_RATE VARCHAR2(200),
    RELEASE_DATE NUMBER,
    CONSTRAINTS PK_PRODUCT_INFO PRIMARY KEY (PRODUCT_NUM)
    );
 
CREATE TABLE PROMOTION_INFO(
    PROMOTION_NUM VARCHAR2(200),
    PROMOTION_PERIOD NUMBER,
    DISCOUNT_RATE VARCHAR2(200),
    CONSTRAINTS PK_PROMOTION_INFO PRIMARY KEY (PROMOTION_NUM)
    );
    
    SELECT *
    FROM TABS;
    
CREATE TABLE PRODUCT_PREFOMANCE(
    REGION_NUM VARCHAR2(200),
    PRODUCT_NUM VARCHAR2(200),
    WEEK_NUM NUMBER,
    QTY NUMBER,
    PROMOTION_NUM VARCHAR2(200),
    CONSTRAINTS PK_PRODUCT_PERFOMANCE PRIMARY KEY (REGION_NUM, PRODUCT_NUM, WEEK_NUM),
    CONSTRAINTS FK_PRODUCT_PREFOMANCE FOREIGN KEY (PROMOTION_NUM) references PROMOTION_INFO(PROMOTION_NUM)
    );
    
SELECT *
FROM PRODUCT_PREFOMANCE;
    
INSERT INTO REGION_INFO
VALUES ('A01','서울');

INSERT INTO REGION_INFO
VALUES ('A02','대전');

SELECT *
FROM REGION_INFO;

INSERT INTO PRODUCT_INFO
VALUES ('ST0001', 'IT-SERVICE', '0.10', 201430);

INSERT INTO PRODUCT_INFO
VALUES ('ST0002', 'FINANCE', '0.15', 201441);

SELECT *
FROM PRODUCT_INFO;

INSERT INTO PROMOTION_INFO
VALUES ('EV0001', 7, '0.3');

INSERT INTO PROMOTION_INFO
VALUES ('EV0002', 5, '0.2');

SELECT *
FROM PROMOTION_INFO;

SELECT *
FROM PRODUCT_PREFOMANCE;

INSERT INTO PRODUCT_PREFOMANCE
VALUES ('A01', 'ST0001', 201501, 9000, 'EV0001');

INSERT INTO PRODUCT_PREFOMANCE
VALUES ('A01', 'ST0001', 201502, 10000, 'EV0002');

--ORA-02291: integrity constraint (KIOTTL.FK_PRODUCT_PREFOMANCE) 
-- violated - parent key not found
INSERT INTO PRODUCT_PREFOMANCE
VALUES ('A01', 'ST0001', 201503, 15000, 'EV0003');

SELECT *
FROM TAB;







    
